### ISSUE TITLE
Running on Windows

### ISSUE THREAD

**Issue by sehnza** [cderinbogaz/inpredo#11]
Hi, 

Having an issue getting train-binary.py to run correctly on windows due to the colons in the weight-improvement section. 
This section : target_dir = "./models/weights-improvement-{epoch:02d}-{val_acc:2f}.hdf5"

Any idea how to get around this?

**Comment by sehnza** [comment]
Screenshot of the issue i'm having: https://imgur.com/a/nanVeau

**Comment by cderinbogaz** [comment]
This is a problem because of the python enviroment you are using. Change the target directory to the exact location instead of a relative path as in the example. For example: "YOUR_PATH_TO_MODELS_FOLDER/models/weights-improvement-{epoch:02d}-{val_acc:2f}.hdf5"

Just go the the folder and check for properties by right clicking and copy the path you see over there to this line.
